repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # v6.0.0
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # pragma: allowlist secret
    hooks:
      - id: check-yaml
        files: ^src/.*\.ya?ml$
  - repo: https://github.com/adrienverge/yamllint
    # v1.38.0
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # pragma: allowlist secret
    hooks:
      - id: yamllint
        files: ^src/.*\.ya?ml$
