repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # v6.0.0
    rev: v6.0.0 # pragma: allowlist secret
    hooks:
      - id: check-yaml
        files: ^src/.*\.ya?ml$
  - repo: https://github.com/adrienverge/yamllint
    # v1.38.0
    rev: v1.38.0 # pragma: allowlist secret
    hooks:
      - id: yamllint
        files: ^src/.*\.ya?ml$
