---
version: 2.1
setup: true

executors:
  pinned-circleci-cli:
    docker:
      # yamllint disable-line rule:line-length
      - image: circleci/circleci-cli:0.1.38646@sha256:2a2081377367e051fb247752ac17f753f7675f5d36e334c24da73034848f0926

jobs:
  validate-orb:
    executor: pinned-circleci-cli
    steps:
      - checkout
      - run:
          name: Pack and validate Orb
          command: scripts/pack-orb.sh

  continue:
    executor: pinned-circleci-cli
    steps:
      - checkout
      - run:
          name: Continue with validated Orb
          command: scripts/continue-circleci.sh

filters: &filters
  branches:
    ignore: release-coordination
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - validate-orb:
          filters: *filters
      - continue:
          requires:
            - validate-orb
          filters: *filters
