version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.3
  shellcheck: circleci/shellcheck@3.2.0

executors:
  pinned-circleci-cli:
    docker:
      - image: circleci/circleci-cli:0.1.38646@sha256:2a2081377367e051fb247752ac17f753f7675f5d36e334c24da73034848f0926

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          executor: pinned-circleci-cli
          filters: *filters
      - orb-tools/review:
          orb_name: vexcalibur-dev/vexcalibur
          filters: *filters
      - shellcheck/check:
          filters: *filters
      - orb-tools/continue:
          executor: pinned-circleci-cli
          pipeline_number: << pipeline.number >>
          vcs_type: github
          orb_name: vexcalibur
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *filters
