version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.3
  shellcheck: circleci/shellcheck@3.2.0

executors:
  pinned-circleci-cli:
    docker:
      - image: circleci/circleci-cli:0.1.38646@sha256:2a2081377367e051fb247752ac17f753f7675f5d36e334c24da73034848f0926

jobs:
  shellcheck:
    docker:
      - image: cimg/base:2026.07@sha256:6b53042171c5eec83d8a9b14206b8483195dde2f3265a85a3d18fe4b778329f3 # pragma: allowlist secret
    steps:
      - checkout
      - shellcheck/install:
          version: "0.11.0"
      - run:
          name: Validate shell
          command: shellcheck scripts/*.sh src/scripts/*.sh

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          executor: pinned-circleci-cli
          filters: *filters
      - orb-tools/review:
          orb_name: vexcalibur-dev/vexcalibur
          filters: *filters
      - shellcheck:
          filters: *filters
      - orb-tools/continue:
          executor: pinned-circleci-cli
          pipeline_number: << pipeline.number >>
          vcs_type: github
          orb_name: vexcalibur
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck
          filters: *filters
